name: ojos_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # data layer
  get_it: ^7.2.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  cupertino_icons: ^1.0.3
  sembast: ^3.1.0+2
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  chewie: ^1.2.2
  sqflite: any

  # UI Layer
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.0.1
  #open_whatsapp: ^0.0.1
  flutter_launcher_icons: ^0.9.1
  persistent_bottom_nav_bar: ^4.0.2
  get: ^4.3.4
  smooth_page_indicator: ^0.3.0-nullsafety.0
  clippy_flutter: ^2.0.0-nullsafety.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  # Is not supported anu more instead we use liquid_ui
  # residemenu: ^1.3.7
  # Liquid is an open source UI toolkit for developing cross platform apps in Flutter.
  # Quickly create apps for Android, IOS, Web or Desktop with our powerful grid system,
  # text processor, forms, extensive prebuilt components and dozens of utilities.
  shrink_sidemenu: ^2.0.0+1-null-safety
  liquid_ui: ^1.0.0+9

  expandable: ^5.0.1
  steps_indicator: ^1.3.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  #  google_map_location_picker: ^4.1.5
  place_picker: ^0.9.19-nullsafety
  geolocator: ^7.4.0
  permission_handler: ^6.0.1+1
  geocoding: ^2.0.0
  image_picker: ^0.8.3+1
  share: ^2.0.4
  #  custom_switch: ^0.0.1
  #  flutter_verification_code: ^0.2.1
  # notification
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.1.1
  google_maps_place_picker: ^2.0.0-nullsafety.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
#  flutter_icons:
#    git: 'https://github.com/jibiel/flutter-icons'
#  balance_swiper:
#    git: 'https://github.com/dietfriends/balance_swiper'
#
#  data_connection_checker:
#    git: 'https://github.com/RounakTadvi/data_connection_checker'
#  modal_progress_hud:
#    git: 'https://github.com/fareesh/modal_progress_hud'
#  residemenu:
#    git: 'https://github.com/MahmoudHassanMustafa/flutter_residemenu'


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^4.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/ojos_logo_app.png"
flutter:
  uses-material-design: true



  assets:
    - assets/locales/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/svg/
    - assets/images/icons/png/
    - assets/images/logo/
    - assets/images/image/
    - assets/images/temp/

  fonts:
    - family: Hacen Tunisia Lt
      fonts:
        - asset: assets/font_family/Hacen-Tunisia-Lt.ttf

    - family: Almarai
      fonts:
        - asset: assets/font_family/Almarai-Regular.ttf
